// <auto-generated/>
// Emik.SourceGenerators.Tattoo, v2.0.7
#pragma warning disable
global using global::System;
global using global::System.Buffers;
global using global::System.Buffers.Binary;
global using global::System.Buffers.Text;
global using global::System.CodeDom;
global using global::System.CodeDom.Compiler;
global using global::System.Collections;
global using global::System.Collections.Concurrent;
global using global::System.Collections.Frozen;
global using global::System.Collections.Generic;
global using global::System.Collections.Immutable;
global using global::System.Collections.ObjectModel;
global using global::System.Collections.Specialized;
global using global::System.ComponentModel;
global using global::System.ComponentModel.DataAnnotations;
global using global::System.ComponentModel.DataAnnotations.Schema;
global using global::System.ComponentModel.Design;
global using global::System.ComponentModel.Design.Serialization;
global using global::System.Configuration;
global using global::System.Configuration.Assemblies;
global using global::System.Configuration.Internal;
global using global::System.Configuration.Provider;
global using global::System.Data;
global using global::System.Data.Common;
global using global::System.Data.Odbc;
global using global::System.Data.OleDb;
global using global::System.Data.Sql;
global using global::System.Data.SqlClient;
global using global::System.Data.SqlTypes;
global using global::System.Diagnostics;
global using global::System.Diagnostics.CodeAnalysis;
global using global::System.Diagnostics.Contracts;
global using global::System.Diagnostics.Eventing;
global using global::System.Diagnostics.Eventing.Reader;
global using global::System.Diagnostics.Metrics;
global using global::System.Diagnostics.PerformanceData;
global using global::System.Diagnostics.SymbolStore;
global using global::System.Diagnostics.Tracing;
global using global::System.Drawing;
global using global::System.Drawing.Configuration;
global using global::System.Drawing.Design;
global using global::System.Drawing.Drawing2D;
global using global::System.Drawing.Imaging;
global using global::System.Drawing.Printing;
global using global::System.Drawing.Text;
global using global::System.Dynamic;
global using global::System.Formats;
global using global::System.Formats.Asn1;
global using global::System.Formats.Tar;
global using global::System.Globalization;
global using global::System.IO;
global using global::System.IO.Compression;
global using global::System.IO.Enumeration;
global using global::System.IO.IsolatedStorage;
global using global::System.IO.MemoryMappedFiles;
global using global::System.IO.Packaging;
global using global::System.IO.Pipelines;
global using global::System.IO.Pipes;
global using global::System.IO.Ports;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::System.Media;
global using global::System.Net;
global using global::System.Net.Cache;
global using global::System.Net.Http;
global using global::System.Net.Http.Headers;
global using global::System.Net.Http.Json;
global using global::System.Net.Http.Metrics;
global using global::System.Net.Mail;
global using global::System.Net.Mime;
global using global::System.Net.NetworkInformation;
global using global::System.Net.PeerToPeer;
global using global::System.Net.PeerToPeer.Collaboration;
global using global::System.Net.Quic;
global using global::System.Net.Security;
global using global::System.Net.Sockets;
global using global::System.Net.WebSockets;
global using global::System.Numerics;
global using global::System.Reflection;
global using global::System.Reflection.Emit;
global using global::System.Reflection.Metadata;
global using global::System.Reflection.Metadata.Ecma335;
global using global::System.Reflection.PortableExecutable;
global using global::System.Resources;
global using global::System.Runtime;
global using global::System.Runtime.CompilerServices;
global using global::System.Runtime.ConstrainedExecution;
global using global::System.Runtime.ExceptionServices;
global using global::System.Runtime.InteropServices;
global using global::System.Runtime.InteropServices.ComTypes;
global using global::System.Runtime.InteropServices.JavaScript;
global using global::System.Runtime.InteropServices.Marshalling;
global using global::System.Runtime.InteropServices.ObjectiveC;
global using global::System.Runtime.InteropServices.Swift;
global using global::System.Runtime.Intrinsics;
global using global::System.Runtime.Intrinsics.Arm;
global using global::System.Runtime.Intrinsics.Wasm;
global using global::System.Runtime.Intrinsics.X86;
global using global::System.Runtime.Loader;
global using global::System.Runtime.Remoting;
global using global::System.Runtime.Serialization;
global using global::System.Runtime.Serialization.DataContracts;
global using global::System.Runtime.Serialization.Formatters;
global using global::System.Runtime.Serialization.Formatters.Binary;
global using global::System.Runtime.Serialization.Json;
global using global::System.Runtime.Versioning;
global using global::System.Security;
global using global::System.Security.AccessControl;
global using global::System.Security.Authentication;
global using global::System.Security.Authentication.ExtendedProtection;
global using global::System.Security.Claims;
global using global::System.Security.Cryptography;
global using global::System.Security.Cryptography.Pkcs;
global using global::System.Security.Cryptography.X509Certificates;
global using global::System.Security.Cryptography.Xml;
global using global::System.Security.Permissions;
global using global::System.Security.Policy;
global using global::System.Security.Principal;
global using global::System.ServiceModel;
global using global::System.ServiceModel.Syndication;
global using global::System.ServiceProcess;
global using global::System.Text;
global using global::System.Text.Encodings;
global using global::System.Text.Encodings.Web;
global using global::System.Text.Json;
global using global::System.Text.Json.Nodes;
global using global::System.Text.Json.Schema;
global using global::System.Text.Json.Serialization;
global using global::System.Text.Json.Serialization.Metadata;
global using global::System.Text.RegularExpressions;
global using global::System.Text.Unicode;
global using global::System.Threading;
global using global::System.Threading.Channels;
global using global::System.Threading.Tasks;
global using global::System.Threading.Tasks.Dataflow;
global using global::System.Threading.Tasks.Sources;
global using global::System.Timers;
global using global::System.Transactions;
global using global::System.Web;
global using global::System.Windows;
global using global::System.Windows.Input;
global using global::System.Windows.Markup;
global using global::System.Xml;
global using global::System.Xml.Linq;
global using global::System.Xml.Resolvers;
global using global::System.Xml.Schema;
global using global::System.Xml.Serialization;
global using global::System.Xml.XPath;
global using global::System.Xml.Xsl;
global using global::AOT;
global using global::Assets;
global using global::Assets.OVR;
global using global::Assets.OVR.Scripts;
global using global::Assets.Prototype;
global using global::Assets.Prototype.GasVent;
global using global::Assets.Scripts;
global using global::Assets.Scripts.AutomatedTesting;
global using global::Assets.Scripts.AutomatedTesting.Reports;
global using global::Assets.Scripts.AutomatedTesting.Solvers;
global using global::Assets.Scripts.AutomatedTesting.TestFixtures;
global using global::Assets.Scripts.BombBinder;
global using global::Assets.Scripts.Components;
global using global::Assets.Scripts.Components.VennWire;
global using global::Assets.Scripts.DemoRecorder;
global using global::Assets.Scripts.DossierMenu;
global using global::Assets.Scripts.Input;
global using global::Assets.Scripts.Leaderboards;
global using global::Assets.Scripts.Lightmapping;
global using global::Assets.Scripts.Logging;
global using global::Assets.Scripts.Manual;
global using global::Assets.Scripts.Menu;
global using global::Assets.Scripts.Menu.Animations;
global using global::Assets.Scripts.Menu.ControlsTutorial;
global using global::Assets.Scripts.Missions;
global using global::Assets.Scripts.Mods;
global using global::Assets.Scripts.Mods.Mission;
global using global::Assets.Scripts.Mods.Screens;
global using global::Assets.Scripts.Pacing;
global using global::Assets.Scripts.Platform;
global using global::Assets.Scripts.Platform.Common;
global using global::Assets.Scripts.Platform.Common.IO;
global using global::Assets.Scripts.Platform.IOS;
global using global::Assets.Scripts.Platform.IOS.IO;
global using global::Assets.Scripts.Platform.Linux;
global using global::Assets.Scripts.Platform.Linux.IO;
global using global::Assets.Scripts.Platform.OSX;
global using global::Assets.Scripts.Platform.OSX.IO;
global using global::Assets.Scripts.Platform.PC;
global using global::Assets.Scripts.Platform.PC.IO;
global using global::Assets.Scripts.Platform.PS4;
global using global::Assets.Scripts.Platform.PS4.IO;
global using global::Assets.Scripts.Progression;
global using global::Assets.Scripts.Props;
global using global::Assets.Scripts.Records;
global using global::Assets.Scripts.Rules;
global using global::Assets.Scripts.Rules.JsonConverters;
global using global::Assets.Scripts.Services;
global using global::Assets.Scripts.Services.Android;
global using global::Assets.Scripts.Services.IOS;
global using global::Assets.Scripts.Services.OculusServices;
global using global::Assets.Scripts.Services.Steam;
global using global::Assets.Scripts.Services.XBoxOne;
global using global::Assets.Scripts.Settings;
global using global::Assets.Scripts.Stats;
global using global::Assets.Scripts.Test;
global using global::Assets.Scripts.Tournaments;
global using global::Assets.Scripts.UI;
global using global::Assets.Scripts.UserManagement;
global using global::Assets.Scripts.Utility;
global using global::Assets.Scripts.VR;
global using global::Assets.Scripts.VR.Null;
global using global::Assets.Scripts.VR.Oculus;
global using global::BasicExample;
global using global::BindingsExample;
global using global::BombGame;
global using global::CommunityToolkit;
global using global::CommunityToolkit.Common;
global using global::CommunityToolkit.Common.Collections;
global using global::CommunityToolkit.Common.Deferred;
global using global::CommunityToolkit.Common.Extensions;
global using global::CommunityToolkit.Common.Helpers;
global using global::CommunityToolkit.Diagnostics;
global using global::CommunityToolkit.Helpers;
global using global::CommunityToolkit.HighPerformance;
global using global::CommunityToolkit.HighPerformance.Buffers;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces;
global using global::CommunityToolkit.HighPerformance.Buffers.Views;
global using global::CommunityToolkit.HighPerformance.Enumerables;
global using global::CommunityToolkit.HighPerformance.Helpers;
global using global::CommunityToolkit.HighPerformance.Helpers.Internals;
global using global::CommunityToolkit.HighPerformance.Memory;
global using global::CommunityToolkit.HighPerformance.Memory.Internals;
global using global::CommunityToolkit.HighPerformance.Memory.Views;
global using global::CommunityToolkit.HighPerformance.Streams;
global using global::DarkTonic;
global using global::DarkTonic.MasterAudio;
global using global::DigitalOpus;
global using global::DigitalOpus.MB;
global using global::DigitalOpus.MB.Core;
global using global::Emik;
global using global::Emik.Morsels;
global using global::Emik.SourceGenerators;
global using global::Emik.SourceGenerators.Choices;
global using global::Emik.SourceGenerators.Choices.Generated;
global using global::Emik.SourceGenerators.Choices.Generated.Tests;
global using global::Events;
global using global::Fody;
global using global::Gu;
global using global::Gu.Roslyn;
global using global::Gu.Roslyn.AnalyzerExtensions;
global using global::Gu.Roslyn.AnalyzerExtensions.StyleCopComparers;
global using global::Gu.Roslyn.CodeFixExtensions;
global using global::Gvr;
global using global::Gvr.Internal;
global using global::I2;
global using global::I2.Loc;
global using global::I2.Loc.SimpleJSON;
global using global::ILMerge;
global using global::InControl;
global using global::InControl.Internal;
global using global::InControl.NativeProfile;
global using global::InlineIL;
global using global::InlineMethod;
global using global::InterfaceMovement;
global using global::JetBrains;
global using global::JetBrains.Annotations;
global using global::KeyboardAndMouseExample;
global using global::Lazy;
global using global::LocalsInit;
global using global::Microsoft;
global using global::Microsoft.CSharp;
global using global::Microsoft.CSharp.RuntimeBinder;
global using global::Microsoft.CodeAnalysis;
global using global::Microsoft.SqlServer;
global using global::Microsoft.SqlServer.Server;
global using global::Microsoft.TestPlatform;
global using global::Microsoft.TestPlatform.PlatformAbstractions;
global using global::Microsoft.VisualBasic;
global using global::Microsoft.VisualBasic.CompilerServices;
global using global::Microsoft.VisualBasic.FileIO;
global using global::Microsoft.VisualStudio;
global using global::Microsoft.VisualStudio.CodeCoverage;
global using global::Microsoft.VisualStudio.TestPlatform;
global using global::Microsoft.VisualStudio.TestPlatform.Common;
global using global::Microsoft.VisualStudio.TestPlatform.Common.DataCollection;
global using global::Microsoft.VisualStudio.TestPlatform.Common.DataCollector;
global using global::Microsoft.VisualStudio.TestPlatform.Common.DataCollector.Interfaces;
global using global::Microsoft.VisualStudio.TestPlatform.Common.Exceptions;
global using global::Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators;
global using global::Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework;
global using global::Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.Utilities;
global using global::Microsoft.VisualStudio.TestPlatform.Common.Filtering;
global using global::Microsoft.VisualStudio.TestPlatform.Common.Hosting;
global using global::Microsoft.VisualStudio.TestPlatform.Common.Interfaces;
global using global::Microsoft.VisualStudio.TestPlatform.Common.Logging;
global using global::Microsoft.VisualStudio.TestPlatform.Common.Resources;
global using global::Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider;
global using global::Microsoft.VisualStudio.TestPlatform.Common.Telemetry;
global using global::Microsoft.VisualStudio.TestPlatform.Common.Utilities;
global using global::Microsoft.VisualStudio.TestPlatform.CommunicationUtilities;
global using global::Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection;
global using global::Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection.Interfaces;
global using global::Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.EventHandlers;
global using global::Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.Interfaces;
global using global::Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.ObjectModel;
global using global::Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.Resources;
global using global::Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.Serialization;
global using global::Microsoft.VisualStudio.TestPlatform.CoreUtilities;
global using global::Microsoft.VisualStudio.TestPlatform.CoreUtilities.Extensions;
global using global::Microsoft.VisualStudio.TestPlatform.CoreUtilities.Helpers;
global using global::Microsoft.VisualStudio.TestPlatform.CoreUtilities.Resources;
global using global::Microsoft.VisualStudio.TestPlatform.CoreUtilities.Tracing;
global using global::Microsoft.VisualStudio.TestPlatform.CoreUtilities.Tracing.Interfaces;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Adapter;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.ArtifactProcessing;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.Parallel;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.EventHandlers;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.Interfaces;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Resources;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.TestRunAttachmentsProcessing;
global using global::Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Utilities;
global using global::Microsoft.VisualStudio.TestPlatform.Execution;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Client;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.Interfaces;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.Payloads;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollector;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollector.InProcDataCollector;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.ClientProtocol;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.TesthostProtocol;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Host;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.InProcDataCollector;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Navigation;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Resources;
global using global::Microsoft.VisualStudio.TestPlatform.ObjectModel.Utilities;
global using global::Microsoft.VisualStudio.TestPlatform.PlatformAbstractions;
global using global::Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.Interfaces;
global using global::Microsoft.VisualStudio.TestPlatform.TestExecutor;
global using global::Microsoft.VisualStudio.TestPlatform.TestHost;
global using global::Microsoft.VisualStudio.TestPlatform.Utilities;
global using global::Microsoft.VisualStudio.TestPlatform.Utilities.Helpers;
global using global::Microsoft.VisualStudio.TestPlatform.Utilities.Helpers.Interfaces;
global using global::Microsoft.VisualStudio.TestPlatform.Utilities.Resources;
global using global::Microsoft.Win32;
global using global::Microsoft.Win32.SafeHandles;
global using global::MultiplayerBasicExample;
global using global::MultiplayerWithBindingsExample;
global using global::Newtonsoft;
global using global::Newtonsoft.Json;
global using global::Newtonsoft.Json.Bson;
global using global::Newtonsoft.Json.Converters;
global using global::Newtonsoft.Json.Linq;
global using global::Newtonsoft.Json.Linq.JsonPath;
global using global::Newtonsoft.Json.Schema;
global using global::Newtonsoft.Json.Serialization;
global using global::Newtonsoft.Json.Utilities;
global using global::NuGetClone;
global using global::NuGetClone.Frameworks;
global using global::NuGetClone.Shared;
global using global::NullGuard;
global using global::NullGuard.CodeAnalysis;
global using global::OVR;
global using global::OVR.OpenVR;
global using global::OVRSimpleJSON;
global using global::Oculus;
global using global::Oculus.Platform;
global using global::Oculus.Platform.Models;
global using global::Oculus.Platform.Samples;
global using global::Oculus.Platform.Samples.EntitlementCheck;
global using global::Oculus.Platform.Samples.NetChat;
global using global::Oculus.Platform.Samples.SimplePlatformSample;
global using global::Oculus.Platform.Samples.VrBoardGame;
global using global::Oculus.Platform.Samples.VrHoops;
global using global::Oculus.Platform.Samples.VrVoiceChat;
global using global::Scifa;
global using global::Scifa.CheckedExceptions;
global using global::Scifa.CheckedExceptions.Attributes;
global using global::Serilog;
global using global::Serilog.Capturing;
global using global::Serilog.Configuration;
global using global::Serilog.Context;
global using global::Serilog.Core;
global using global::Serilog.Core.Enrichers;
global using global::Serilog.Core.Filters;
global using global::Serilog.Core.Pipeline;
global using global::Serilog.Core.Sinks;
global using global::Serilog.Core.Sinks.Batching;
global using global::Serilog.Data;
global using global::Serilog.Debugging;
global using global::Serilog.Events;
global using global::Serilog.Filters;
global using global::Serilog.Formatting;
global using global::Serilog.Formatting.Compact;
global using global::Serilog.Formatting.Display;
global using global::Serilog.Formatting.Json;
global using global::Serilog.Parsing;
global using global::Serilog.Policies;
global using global::Serilog.Rendering;
global using global::Serilog.Settings;
global using global::Serilog.Settings.KeyValuePairs;
global using global::Serilog.Sinks;
global using global::Serilog.Sinks.File;
global using global::Serilog.Sinks.SystemConsole;
global using global::Serilog.Sinks.SystemConsole.Formatting;
global using global::Serilog.Sinks.SystemConsole.Output;
global using global::Serilog.Sinks.SystemConsole.Platform;
global using global::Serilog.Sinks.SystemConsole.Rendering;
global using global::Serilog.Sinks.SystemConsole.Themes;
global using global::SimpleJSON;
global using global::SimpleJson;
global using global::SimpleJson.Reflection;
global using global::Substitute;
global using global::TMPro;
global using global::TMPro.SpriteAssetUtilities;
global using global::TouchExample;
global using global::UnitGenerator;
global using global::UnityEditor;
global using global::UnityEditor.AI;
global using global::UnityEditor.Accessibility;
global using global::UnityEditor.Advertisements;
global using global::UnityEditor.Analytics;
global using global::UnityEditor.AnimatedValues;
global using global::UnityEditor.Animations;
global using global::UnityEditor.Audio;
global using global::UnityEditor.Build;
global using global::UnityEditor.BuildReporting;
global using global::UnityEditor.Callbacks;
global using global::UnityEditor.CloudBuild;
global using global::UnityEditor.Collaboration;
global using global::UnityEditor.Compilation;
global using global::UnityEditor.Connect;
global using global::UnityEditor.CrashReporting;
global using global::UnityEditor.DeploymentTargets;
global using global::UnityEditor.Events;
global using global::UnityEditor.Experimental;
global using global::UnityEditor.Experimental.Animations;
global using global::UnityEditor.Experimental.AssetImporters;
global using global::UnityEditor.Experimental.Build;
global using global::UnityEditor.Experimental.Build.AssetBundle;
global using global::UnityEditor.Experimental.Build.Player;
global using global::UnityEditor.Experimental.U2D;
global using global::UnityEditor.Experimental.UIElements;
global using global::UnityEditor.Experimental.UIElements.Debugger;
global using global::UnityEditor.Experimental.UIElements.GraphView;
global using global::UnityEditor.Hardware;
global using global::UnityEditor.IMGUI;
global using global::UnityEditor.IMGUI.Controls;
global using global::UnityEditor.Macros;
global using global::UnityEditor.Media;
global using global::UnityEditor.MemoryProfiler;
global using global::UnityEditor.Modules;
global using global::UnityEditor.Networking;
global using global::UnityEditor.Networking.PlayerConnection;
global using global::UnityEditor.PackageManager;
global using global::UnityEditor.PackageManager.Requests;
global using global::UnityEditor.ProjectWindowCallback;
global using global::UnityEditor.Purchasing;
global using global::UnityEditor.Rendering;
global using global::UnityEditor.RestService;
global using global::UnityEditor.SceneManagement;
global using global::UnityEditor.Scripting;
global using global::UnityEditor.Scripting.Compilers;
global using global::UnityEditor.Scripting.ScriptCompilation;
global using global::UnityEditor.Scripting.Serialization;
global using global::UnityEditor.Sprites;
global using global::UnityEditor.StyleSheets;
global using global::UnityEditor.TreeViewExamples;
global using global::UnityEditor.U2D;
global using global::UnityEditor.U2D.Common;
global using global::UnityEditor.U2D.Interface;
global using global::UnityEditor.Utils;
global using global::UnityEditor.VersionControl;
global using global::UnityEditor.VisualStudioIntegration;
global using global::UnityEditor.Web;
global using global::UnityEditor.XR;
global using global::UnityEditor.XR.Daydream;
global using global::UnityEditorInternal;
global using global::UnityEditorInternal.VR;
global using global::UnityEditorInternal.VersionControl;
global using global::UnityEngine;
global using global::UnityEngine.AI;
global using global::UnityEngine.Accessibility;
global using global::UnityEngine.Advertisements;
global using global::UnityEngine.Analytics;
global using global::UnityEngine.Animations;
global using global::UnityEngine.Apple;
global using global::UnityEngine.Apple.ReplayKit;
global using global::UnityEngine.Apple.TV;
global using global::UnityEngine.Assertions;
global using global::UnityEngine.Assertions.Comparers;
global using global::UnityEngine.Assertions.Must;
global using global::UnityEngine.Audio;
global using global::UnityEngine.Bindings;
global using global::UnityEngine.CSSLayout;
global using global::UnityEngine.Collections;
global using global::UnityEngine.Connect;
global using global::UnityEngine.CrashReportHandler;
global using global::UnityEngine.Diagnostics;
global using global::UnityEngine.EventSystems;
global using global::UnityEngine.Events;
global using global::UnityEngine.Experimental;
global using global::UnityEngine.Experimental.Playables;
global using global::UnityEngine.Experimental.Rendering;
global using global::UnityEngine.Experimental.U2D;
global using global::UnityEngine.Experimental.UIElements;
global using global::UnityEngine.Experimental.UIElements.StyleEnums;
global using global::UnityEngine.Experimental.UIElements.StyleSheets;
global using global::UnityEngine.Experimental.Video;
global using global::UnityEngine.Experimental.XR;
global using global::UnityEngine.Internal;
global using global::UnityEngine.Internal.VR;
global using global::UnityEngine.Networking;
global using global::UnityEngine.Networking.Match;
global using global::UnityEngine.Networking.PlayerConnection;
global using global::UnityEngine.Networking.Types;
global using global::UnityEngine.Playables;
global using global::UnityEngine.Profiling;
global using global::UnityEngine.Rendering;
global using global::UnityEngine.SceneManagement;
global using global::UnityEngine.Scripting;
global using global::UnityEngine.Scripting.APIUpdating;
global using global::UnityEngine.Serialization;
global using global::UnityEngine.SocialPlatforms;
global using global::UnityEngine.SocialPlatforms.GameCenter;
global using global::UnityEngine.SocialPlatforms.Impl;
global using global::UnityEngine.Sprites;
global using global::UnityEngine.StyleSheets;
global using global::UnityEngine.Tilemaps;
global using global::UnityEngine.Tizen;
global using global::UnityEngine.U2D;
global using global::UnityEngine.U2D.Interface;
global using global::UnityEngine.VR;
global using global::UnityEngine.Video;
global using global::UnityEngine.WSA;
global using global::UnityEngine.Windows;
global using global::UnityEngine.Windows.Speech;
global using global::UnityEngine.XR;
global using global::UnityEngine.XR.Tango;
global using global::UnityEngine.XR.WSA;
global using global::UnityEngine.XR.WSA.Input;
global using global::UnityEngine.XR.WSA.Persistence;
global using global::UnityEngine.XR.WSA.Sharing;
global using global::UnityEngine.XR.WSA.WebCam;
global using global::UnityEngine.iOS;
global using global::UnityEngineInternal;
global using global::UnityEngineInternal.Input;
global using global::VirtualDeviceExample;
global using global::Virtuosity;
global using global::Xunit;
global using global::Xunit.Abstractions;
global using global::Xunit.Extensions;
global using global::Xunit.Internal;
global using global::Xunit.Sdk;
global using global::Xunit.Serialization;
global using global::nn;
global using global::nn.nifm;
global using global::proto;
global using global::proto.Proto;

// Polyfills of namespaces in case dependencies are conditional.
namespace System { }

namespace System.Buffers { }

namespace System.Buffers.Binary { }

namespace System.Buffers.Text { }

namespace System.CodeDom { }

namespace System.CodeDom.Compiler { }

namespace System.Collections { }

namespace System.Collections.Concurrent { }

namespace System.Collections.Frozen { }

namespace System.Collections.Generic { }

namespace System.Collections.Immutable { }

namespace System.Collections.ObjectModel { }

namespace System.Collections.Specialized { }

namespace System.ComponentModel { }

namespace System.ComponentModel.DataAnnotations { }

namespace System.ComponentModel.DataAnnotations.Schema { }

namespace System.ComponentModel.Design { }

namespace System.ComponentModel.Design.Serialization { }

namespace System.Configuration { }

namespace System.Configuration.Assemblies { }

namespace System.Configuration.Internal { }

namespace System.Configuration.Provider { }

namespace System.Data { }

namespace System.Data.Common { }

namespace System.Data.Odbc { }

namespace System.Data.OleDb { }

namespace System.Data.Sql { }

namespace System.Data.SqlClient { }

namespace System.Data.SqlTypes { }

namespace System.Diagnostics { }

namespace System.Diagnostics.CodeAnalysis { }

namespace System.Diagnostics.Contracts { }

namespace System.Diagnostics.Eventing { }

namespace System.Diagnostics.Eventing.Reader { }

namespace System.Diagnostics.Metrics { }

namespace System.Diagnostics.PerformanceData { }

namespace System.Diagnostics.SymbolStore { }

namespace System.Diagnostics.Tracing { }

namespace System.Drawing { }

namespace System.Drawing.Configuration { }

namespace System.Drawing.Design { }

namespace System.Drawing.Drawing2D { }

namespace System.Drawing.Imaging { }

namespace System.Drawing.Printing { }

namespace System.Drawing.Text { }

namespace System.Dynamic { }

namespace System.Formats { }

namespace System.Formats.Asn1 { }

namespace System.Formats.Tar { }

namespace System.Globalization { }

namespace System.IO { }

namespace System.IO.Compression { }

namespace System.IO.Enumeration { }

namespace System.IO.IsolatedStorage { }

namespace System.IO.MemoryMappedFiles { }

namespace System.IO.Packaging { }

namespace System.IO.Pipelines { }

namespace System.IO.Pipes { }

namespace System.IO.Ports { }

namespace System.Linq { }

namespace System.Linq.Expressions { }

namespace System.Media { }

namespace System.Net { }

namespace System.Net.Cache { }

namespace System.Net.Http { }

namespace System.Net.Http.Headers { }

namespace System.Net.Http.Json { }

namespace System.Net.Http.Metrics { }

namespace System.Net.Mail { }

namespace System.Net.Mime { }

namespace System.Net.NetworkInformation { }

namespace System.Net.PeerToPeer { }

namespace System.Net.PeerToPeer.Collaboration { }

namespace System.Net.Quic { }

namespace System.Net.Security { }

namespace System.Net.Sockets { }

namespace System.Net.WebSockets { }

namespace System.Numerics { }

namespace System.Reflection { }

namespace System.Reflection.Emit { }

namespace System.Reflection.Metadata { }

namespace System.Reflection.Metadata.Ecma335 { }

namespace System.Reflection.PortableExecutable { }

namespace System.Resources { }

namespace System.Runtime { }

namespace System.Runtime.CompilerServices { }

namespace System.Runtime.ConstrainedExecution { }

namespace System.Runtime.ExceptionServices { }

namespace System.Runtime.InteropServices { }

namespace System.Runtime.InteropServices.ComTypes { }

namespace System.Runtime.InteropServices.JavaScript { }

namespace System.Runtime.InteropServices.Marshalling { }

namespace System.Runtime.InteropServices.ObjectiveC { }

namespace System.Runtime.InteropServices.Swift { }

namespace System.Runtime.Intrinsics { }

namespace System.Runtime.Intrinsics.Arm { }

namespace System.Runtime.Intrinsics.Wasm { }

namespace System.Runtime.Intrinsics.X86 { }

namespace System.Runtime.Loader { }

namespace System.Runtime.Remoting { }

namespace System.Runtime.Serialization { }

namespace System.Runtime.Serialization.DataContracts { }

namespace System.Runtime.Serialization.Formatters { }

namespace System.Runtime.Serialization.Formatters.Binary { }

namespace System.Runtime.Serialization.Json { }

namespace System.Runtime.Versioning { }

namespace System.Security { }

namespace System.Security.AccessControl { }

namespace System.Security.Authentication { }

namespace System.Security.Authentication.ExtendedProtection { }

namespace System.Security.Claims { }

namespace System.Security.Cryptography { }

namespace System.Security.Cryptography.Pkcs { }

namespace System.Security.Cryptography.X509Certificates { }

namespace System.Security.Cryptography.Xml { }

namespace System.Security.Permissions { }

namespace System.Security.Policy { }

namespace System.Security.Principal { }

namespace System.ServiceModel { }

namespace System.ServiceModel.Syndication { }

namespace System.ServiceProcess { }

namespace System.Text { }

namespace System.Text.Encodings { }

namespace System.Text.Encodings.Web { }

namespace System.Text.Json { }

namespace System.Text.Json.Nodes { }

namespace System.Text.Json.Schema { }

namespace System.Text.Json.Serialization { }

namespace System.Text.Json.Serialization.Metadata { }

namespace System.Text.RegularExpressions { }

namespace System.Text.Unicode { }

namespace System.Threading { }

namespace System.Threading.Channels { }

namespace System.Threading.Tasks { }

namespace System.Threading.Tasks.Dataflow { }

namespace System.Threading.Tasks.Sources { }

namespace System.Timers { }

namespace System.Transactions { }

namespace System.Web { }

namespace System.Windows { }

namespace System.Windows.Input { }

namespace System.Windows.Markup { }

namespace System.Xml { }

namespace System.Xml.Linq { }

namespace System.Xml.Resolvers { }

namespace System.Xml.Schema { }

namespace System.Xml.Serialization { }

namespace System.Xml.XPath { }

namespace System.Xml.Xsl { }

namespace AOT { }

namespace Assets { }

namespace Assets.OVR { }

namespace Assets.OVR.Scripts { }

namespace Assets.Prototype { }

namespace Assets.Prototype.GasVent { }

namespace Assets.Scripts { }

namespace Assets.Scripts.AutomatedTesting { }

namespace Assets.Scripts.AutomatedTesting.Reports { }

namespace Assets.Scripts.AutomatedTesting.Solvers { }

namespace Assets.Scripts.AutomatedTesting.TestFixtures { }

namespace Assets.Scripts.BombBinder { }

namespace Assets.Scripts.Components { }

namespace Assets.Scripts.Components.VennWire { }

namespace Assets.Scripts.DemoRecorder { }

namespace Assets.Scripts.DossierMenu { }

namespace Assets.Scripts.Input { }

namespace Assets.Scripts.Leaderboards { }

namespace Assets.Scripts.Lightmapping { }

namespace Assets.Scripts.Logging { }

namespace Assets.Scripts.Manual { }

namespace Assets.Scripts.Menu { }

namespace Assets.Scripts.Menu.Animations { }

namespace Assets.Scripts.Menu.ControlsTutorial { }

namespace Assets.Scripts.Missions { }

namespace Assets.Scripts.Mods { }

namespace Assets.Scripts.Mods.Mission { }

namespace Assets.Scripts.Mods.Screens { }

namespace Assets.Scripts.Pacing { }

namespace Assets.Scripts.Platform { }

namespace Assets.Scripts.Platform.Common { }

namespace Assets.Scripts.Platform.Common.IO { }

namespace Assets.Scripts.Platform.IOS { }

namespace Assets.Scripts.Platform.IOS.IO { }

namespace Assets.Scripts.Platform.Linux { }

namespace Assets.Scripts.Platform.Linux.IO { }

namespace Assets.Scripts.Platform.OSX { }

namespace Assets.Scripts.Platform.OSX.IO { }

namespace Assets.Scripts.Platform.PC { }

namespace Assets.Scripts.Platform.PC.IO { }

namespace Assets.Scripts.Platform.PS4 { }

namespace Assets.Scripts.Platform.PS4.IO { }

namespace Assets.Scripts.Progression { }

namespace Assets.Scripts.Props { }

namespace Assets.Scripts.Records { }

namespace Assets.Scripts.Rules { }

namespace Assets.Scripts.Rules.JsonConverters { }

namespace Assets.Scripts.Services { }

namespace Assets.Scripts.Services.Android { }

namespace Assets.Scripts.Services.IOS { }

namespace Assets.Scripts.Services.OculusServices { }

namespace Assets.Scripts.Services.Steam { }

namespace Assets.Scripts.Services.XBoxOne { }

namespace Assets.Scripts.Settings { }

namespace Assets.Scripts.Stats { }

namespace Assets.Scripts.Test { }

namespace Assets.Scripts.Tournaments { }

namespace Assets.Scripts.UI { }

namespace Assets.Scripts.UserManagement { }

namespace Assets.Scripts.Utility { }

namespace Assets.Scripts.VR { }

namespace Assets.Scripts.VR.Null { }

namespace Assets.Scripts.VR.Oculus { }

namespace BasicExample { }

namespace BindingsExample { }

namespace BombGame { }

namespace CommunityToolkit { }

namespace CommunityToolkit.Common { }

namespace CommunityToolkit.Common.Collections { }

namespace CommunityToolkit.Common.Deferred { }

namespace CommunityToolkit.Common.Extensions { }

namespace CommunityToolkit.Common.Helpers { }

namespace CommunityToolkit.Diagnostics { }

namespace CommunityToolkit.Helpers { }

namespace CommunityToolkit.HighPerformance { }

namespace CommunityToolkit.HighPerformance.Buffers { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces { }

namespace CommunityToolkit.HighPerformance.Buffers.Views { }

namespace CommunityToolkit.HighPerformance.Enumerables { }

namespace CommunityToolkit.HighPerformance.Helpers { }

namespace CommunityToolkit.HighPerformance.Helpers.Internals { }

namespace CommunityToolkit.HighPerformance.Memory { }

namespace CommunityToolkit.HighPerformance.Memory.Internals { }

namespace CommunityToolkit.HighPerformance.Memory.Views { }

namespace CommunityToolkit.HighPerformance.Streams { }

namespace DarkTonic { }

namespace DarkTonic.MasterAudio { }

namespace DigitalOpus { }

namespace DigitalOpus.MB { }

namespace DigitalOpus.MB.Core { }

namespace Emik { }

namespace Emik.Morsels { }

namespace Emik.SourceGenerators { }

namespace Emik.SourceGenerators.Choices { }

namespace Emik.SourceGenerators.Choices.Generated { }

namespace Emik.SourceGenerators.Choices.Generated.Tests { }

namespace Events { }

namespace Fody { }

namespace Gu { }

namespace Gu.Roslyn { }

namespace Gu.Roslyn.AnalyzerExtensions { }

namespace Gu.Roslyn.AnalyzerExtensions.StyleCopComparers { }

namespace Gu.Roslyn.CodeFixExtensions { }

namespace Gvr { }

namespace Gvr.Internal { }

namespace I2 { }

namespace I2.Loc { }

namespace I2.Loc.SimpleJSON { }

namespace ILMerge { }

namespace InControl { }

namespace InControl.Internal { }

namespace InControl.NativeProfile { }

namespace InlineIL { }

namespace InlineMethod { }

namespace InterfaceMovement { }

namespace JetBrains { }

namespace JetBrains.Annotations { }

namespace KeyboardAndMouseExample { }

namespace Lazy { }

namespace LocalsInit { }

namespace Microsoft { }

namespace Microsoft.CSharp { }

namespace Microsoft.CSharp.RuntimeBinder { }

namespace Microsoft.CodeAnalysis { }

namespace Microsoft.SqlServer { }

namespace Microsoft.SqlServer.Server { }

namespace Microsoft.TestPlatform { }

namespace Microsoft.TestPlatform.PlatformAbstractions { }

namespace Microsoft.VisualBasic { }

namespace Microsoft.VisualBasic.CompilerServices { }

namespace Microsoft.VisualBasic.FileIO { }

namespace Microsoft.VisualStudio { }

namespace Microsoft.VisualStudio.CodeCoverage { }

namespace Microsoft.VisualStudio.TestPlatform { }

namespace Microsoft.VisualStudio.TestPlatform.Common { }

namespace Microsoft.VisualStudio.TestPlatform.Common.DataCollection { }

namespace Microsoft.VisualStudio.TestPlatform.Common.DataCollector { }

namespace Microsoft.VisualStudio.TestPlatform.Common.DataCollector.Interfaces { }

namespace Microsoft.VisualStudio.TestPlatform.Common.Exceptions { }

namespace Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators { }

namespace Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework { }

namespace Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.Utilities { }

namespace Microsoft.VisualStudio.TestPlatform.Common.Filtering { }

namespace Microsoft.VisualStudio.TestPlatform.Common.Hosting { }

namespace Microsoft.VisualStudio.TestPlatform.Common.Interfaces { }

namespace Microsoft.VisualStudio.TestPlatform.Common.Logging { }

namespace Microsoft.VisualStudio.TestPlatform.Common.Resources { }

namespace Microsoft.VisualStudio.TestPlatform.Common.SettingsProvider { }

namespace Microsoft.VisualStudio.TestPlatform.Common.Telemetry { }

namespace Microsoft.VisualStudio.TestPlatform.Common.Utilities { }

namespace Microsoft.VisualStudio.TestPlatform.CommunicationUtilities { }

namespace Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection { }

namespace Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection.Interfaces { }

namespace Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.EventHandlers { }

namespace Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.Interfaces { }

namespace Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.ObjectModel { }

namespace Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.Resources { }

namespace Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.Serialization { }

namespace Microsoft.VisualStudio.TestPlatform.CoreUtilities { }

namespace Microsoft.VisualStudio.TestPlatform.CoreUtilities.Extensions { }

namespace Microsoft.VisualStudio.TestPlatform.CoreUtilities.Helpers { }

namespace Microsoft.VisualStudio.TestPlatform.CoreUtilities.Resources { }

namespace Microsoft.VisualStudio.TestPlatform.CoreUtilities.Tracing { }

namespace Microsoft.VisualStudio.TestPlatform.CoreUtilities.Tracing.Interfaces { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Adapter { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.ArtifactProcessing { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.Parallel { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.Interfaces { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.EventHandlers { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.Interfaces { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Resources { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.TestRunAttachmentsProcessing { }

namespace Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Utilities { }

namespace Microsoft.VisualStudio.TestPlatform.Execution { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Client { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.Interfaces { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.Payloads { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollector { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollector.InProcDataCollector { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.ClientProtocol { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.TesthostProtocol { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Host { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.InProcDataCollector { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Navigation { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Resources { }

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Utilities { }

namespace Microsoft.VisualStudio.TestPlatform.PlatformAbstractions { }

namespace Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.Interfaces { }

namespace Microsoft.VisualStudio.TestPlatform.TestExecutor { }

namespace Microsoft.VisualStudio.TestPlatform.TestHost { }

namespace Microsoft.VisualStudio.TestPlatform.Utilities { }

namespace Microsoft.VisualStudio.TestPlatform.Utilities.Helpers { }

namespace Microsoft.VisualStudio.TestPlatform.Utilities.Helpers.Interfaces { }

namespace Microsoft.VisualStudio.TestPlatform.Utilities.Resources { }

namespace Microsoft.Win32 { }

namespace Microsoft.Win32.SafeHandles { }

namespace MultiplayerBasicExample { }

namespace MultiplayerWithBindingsExample { }

namespace Newtonsoft { }

namespace Newtonsoft.Json { }

namespace Newtonsoft.Json.Bson { }

namespace Newtonsoft.Json.Converters { }

namespace Newtonsoft.Json.Linq { }

namespace Newtonsoft.Json.Linq.JsonPath { }

namespace Newtonsoft.Json.Schema { }

namespace Newtonsoft.Json.Serialization { }

namespace Newtonsoft.Json.Utilities { }

namespace NuGetClone { }

namespace NuGetClone.Frameworks { }

namespace NuGetClone.Shared { }

namespace NullGuard { }

namespace NullGuard.CodeAnalysis { }

namespace OVR { }

namespace OVR.OpenVR { }

namespace OVRSimpleJSON { }

namespace Oculus { }

namespace Oculus.Platform { }

namespace Oculus.Platform.Models { }

namespace Oculus.Platform.Samples { }

namespace Oculus.Platform.Samples.EntitlementCheck { }

namespace Oculus.Platform.Samples.NetChat { }

namespace Oculus.Platform.Samples.SimplePlatformSample { }

namespace Oculus.Platform.Samples.VrBoardGame { }

namespace Oculus.Platform.Samples.VrHoops { }

namespace Oculus.Platform.Samples.VrVoiceChat { }

namespace Scifa { }

namespace Scifa.CheckedExceptions { }

namespace Scifa.CheckedExceptions.Attributes { }

namespace Serilog { }

namespace Serilog.Capturing { }

namespace Serilog.Configuration { }

namespace Serilog.Context { }

namespace Serilog.Core { }

namespace Serilog.Core.Enrichers { }

namespace Serilog.Core.Filters { }

namespace Serilog.Core.Pipeline { }

namespace Serilog.Core.Sinks { }

namespace Serilog.Core.Sinks.Batching { }

namespace Serilog.Data { }

namespace Serilog.Debugging { }

namespace Serilog.Events { }

namespace Serilog.Filters { }

namespace Serilog.Formatting { }

namespace Serilog.Formatting.Compact { }

namespace Serilog.Formatting.Display { }

namespace Serilog.Formatting.Json { }

namespace Serilog.Parsing { }

namespace Serilog.Policies { }

namespace Serilog.Rendering { }

namespace Serilog.Settings { }

namespace Serilog.Settings.KeyValuePairs { }

namespace Serilog.Sinks { }

namespace Serilog.Sinks.File { }

namespace Serilog.Sinks.SystemConsole { }

namespace Serilog.Sinks.SystemConsole.Formatting { }

namespace Serilog.Sinks.SystemConsole.Output { }

namespace Serilog.Sinks.SystemConsole.Platform { }

namespace Serilog.Sinks.SystemConsole.Rendering { }

namespace Serilog.Sinks.SystemConsole.Themes { }

namespace SimpleJSON { }

namespace SimpleJson { }

namespace SimpleJson.Reflection { }

namespace Substitute { }

namespace TMPro { }

namespace TMPro.SpriteAssetUtilities { }

namespace TouchExample { }

namespace UnitGenerator { }

namespace UnityEditor { }

namespace UnityEditor.AI { }

namespace UnityEditor.Accessibility { }

namespace UnityEditor.Advertisements { }

namespace UnityEditor.Analytics { }

namespace UnityEditor.AnimatedValues { }

namespace UnityEditor.Animations { }

namespace UnityEditor.Audio { }

namespace UnityEditor.Build { }

namespace UnityEditor.BuildReporting { }

namespace UnityEditor.Callbacks { }

namespace UnityEditor.CloudBuild { }

namespace UnityEditor.Collaboration { }

namespace UnityEditor.Compilation { }

namespace UnityEditor.Connect { }

namespace UnityEditor.CrashReporting { }

namespace UnityEditor.DeploymentTargets { }

namespace UnityEditor.Events { }

namespace UnityEditor.Experimental { }

namespace UnityEditor.Experimental.Animations { }

namespace UnityEditor.Experimental.AssetImporters { }

namespace UnityEditor.Experimental.Build { }

namespace UnityEditor.Experimental.Build.AssetBundle { }

namespace UnityEditor.Experimental.Build.Player { }

namespace UnityEditor.Experimental.U2D { }

namespace UnityEditor.Experimental.UIElements { }

namespace UnityEditor.Experimental.UIElements.Debugger { }

namespace UnityEditor.Experimental.UIElements.GraphView { }

namespace UnityEditor.Hardware { }

namespace UnityEditor.IMGUI { }

namespace UnityEditor.IMGUI.Controls { }

namespace UnityEditor.Macros { }

namespace UnityEditor.Media { }

namespace UnityEditor.MemoryProfiler { }

namespace UnityEditor.Modules { }

namespace UnityEditor.Networking { }

namespace UnityEditor.Networking.PlayerConnection { }

namespace UnityEditor.PackageManager { }

namespace UnityEditor.PackageManager.Requests { }

namespace UnityEditor.ProjectWindowCallback { }

namespace UnityEditor.Purchasing { }

namespace UnityEditor.Rendering { }

namespace UnityEditor.RestService { }

namespace UnityEditor.SceneManagement { }

namespace UnityEditor.Scripting { }

namespace UnityEditor.Scripting.Compilers { }

namespace UnityEditor.Scripting.ScriptCompilation { }

namespace UnityEditor.Scripting.Serialization { }

namespace UnityEditor.Sprites { }

namespace UnityEditor.StyleSheets { }

namespace UnityEditor.TreeViewExamples { }

namespace UnityEditor.U2D { }

namespace UnityEditor.U2D.Common { }

namespace UnityEditor.U2D.Interface { }

namespace UnityEditor.Utils { }

namespace UnityEditor.VersionControl { }

namespace UnityEditor.VisualStudioIntegration { }

namespace UnityEditor.Web { }

namespace UnityEditor.XR { }

namespace UnityEditor.XR.Daydream { }

namespace UnityEditorInternal { }

namespace UnityEditorInternal.VR { }

namespace UnityEditorInternal.VersionControl { }

namespace UnityEngine { }

namespace UnityEngine.AI { }

namespace UnityEngine.Accessibility { }

namespace UnityEngine.Advertisements { }

namespace UnityEngine.Analytics { }

namespace UnityEngine.Animations { }

namespace UnityEngine.Apple { }

namespace UnityEngine.Apple.ReplayKit { }

namespace UnityEngine.Apple.TV { }

namespace UnityEngine.Assertions { }

namespace UnityEngine.Assertions.Comparers { }

namespace UnityEngine.Assertions.Must { }

namespace UnityEngine.Audio { }

namespace UnityEngine.Bindings { }

namespace UnityEngine.CSSLayout { }

namespace UnityEngine.Collections { }

namespace UnityEngine.Connect { }

namespace UnityEngine.CrashReportHandler { }

namespace UnityEngine.Diagnostics { }

namespace UnityEngine.EventSystems { }

namespace UnityEngine.Events { }

namespace UnityEngine.Experimental { }

namespace UnityEngine.Experimental.Playables { }

namespace UnityEngine.Experimental.Rendering { }

namespace UnityEngine.Experimental.U2D { }

namespace UnityEngine.Experimental.UIElements { }

namespace UnityEngine.Experimental.UIElements.StyleEnums { }

namespace UnityEngine.Experimental.UIElements.StyleSheets { }

namespace UnityEngine.Experimental.Video { }

namespace UnityEngine.Experimental.XR { }

namespace UnityEngine.Internal { }

namespace UnityEngine.Internal.VR { }

namespace UnityEngine.Networking { }

namespace UnityEngine.Networking.Match { }

namespace UnityEngine.Networking.PlayerConnection { }

namespace UnityEngine.Networking.Types { }

namespace UnityEngine.Playables { }

namespace UnityEngine.Profiling { }

namespace UnityEngine.Rendering { }

namespace UnityEngine.SceneManagement { }

namespace UnityEngine.Scripting { }

namespace UnityEngine.Scripting.APIUpdating { }

namespace UnityEngine.Serialization { }

namespace UnityEngine.SocialPlatforms { }

namespace UnityEngine.SocialPlatforms.GameCenter { }

namespace UnityEngine.SocialPlatforms.Impl { }

namespace UnityEngine.Sprites { }

namespace UnityEngine.StyleSheets { }

namespace UnityEngine.Tilemaps { }

namespace UnityEngine.Tizen { }

namespace UnityEngine.U2D { }

namespace UnityEngine.U2D.Interface { }

namespace UnityEngine.VR { }

namespace UnityEngine.Video { }

namespace UnityEngine.WSA { }

namespace UnityEngine.Windows { }

namespace UnityEngine.Windows.Speech { }

namespace UnityEngine.XR { }

namespace UnityEngine.XR.Tango { }

namespace UnityEngine.XR.WSA { }

namespace UnityEngine.XR.WSA.Input { }

namespace UnityEngine.XR.WSA.Persistence { }

namespace UnityEngine.XR.WSA.Sharing { }

namespace UnityEngine.XR.WSA.WebCam { }

namespace UnityEngine.iOS { }

namespace UnityEngineInternal { }

namespace UnityEngineInternal.Input { }

namespace VirtualDeviceExample { }

namespace Virtuosity { }

namespace Xunit { }

namespace Xunit.Abstractions { }

namespace Xunit.Extensions { }

namespace Xunit.Internal { }

namespace Xunit.Sdk { }

namespace Xunit.Serialization { }

namespace nn { }

namespace nn.nifm { }

namespace proto { }

namespace proto.Proto { }
